### ISSUE TITLE
Request to add required packages

### ISSUE THREAD

**Issue by TangYiChing** [harryjo97/EHGNN#4]
Hi, 

There are some missing references for the provided scripts. Is it possible to list at least the following packages required for classification_TU.sh, classification_OGB.sh, and classification_ZINC.sh? Thanks.

```{python}
$ sh ./scripts/classification_TU.sh 9 000
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main(work_type_parser.parse_known_args()[0])
  File "main.py", line 7, in main
    from trainers.classification_TU import Trainer
  File "/home/EHGNN/trainers/classification_TU.py", line 6, in <module>
    **f**rom transformers.optimization import get_cosine_schedule_with_warmup
ModuleNotFoundError: No module named 'transformers'****

$ sh ./scripts/classification_OGB.sh 9 000
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main(work_type_parser.parse_known_args()[0])
  File "main.py", line 11, in main
    from trainers.classification_OGB import Trainer
  File "/home/EHGNN/trainers/classification_OGB.py", line 5, in <module>
    from ogb.graphproppred import Evaluator
ModuleNotFoundError: No module named 'ogb'

$ sh ./scripts/reconstruction_ZINC.sh 9 000
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main(work_type_parser.parse_known_args()[0])
  File "main.py", line 15, in main
    from trainers.reconstruction_ZINC import Trainer
  File "/home/EHGNN/trainers/reconstruction_ZINC.py", line 6, in <module>
    from torch_geometric.utils import to_dense_adj
ModuleNotFoundError: No module named 'torch_geometric'
```

**Comment by harryjo97** [comment]
Hi TangYiching, 

We have uploaded requirements.txt and added a description for the dependencies in README.md.
